# Generated by Django 6.0 on 2026-01-14 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_pickuprequest_payment_method'),
        ('wallet', '0002_transaction_external_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(help_text='Must match material_type in PickupRequest', max_length=100, unique=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='Percentage (e.g., 20.00 for 20%)', max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='momo_network',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='momo_phone',
        ),
        migrations.AddField(
            model_name='transaction',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='logistics.pickuprequest'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='Lock wallet for suspicious activity'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Negative for debits, Positive for credits', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('JOB_EARNING', 'Job Earning'), ('COMMISSION_DEDUCTION', 'Commission Deduction'), ('PENALTY', 'Penalty'), ('REFUND', 'Refund')], max_length=30),
        ),
    ]
