# Generated by Django 6.0 on 2026-01-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_commissionrule_remove_transaction_external_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='trust_score',
            field=models.IntegerField(default=100, help_text='0-100 score based on payment history'),
        ),
    ]
