# Generated by Django 6.0 on 2026-02-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('JOB_EARNING', 'Job Earning'), ('SALE_EARNING', 'Sale Earning'), ('COMMISSION_DEDUCTION', 'Commission Deduction'), ('PENALTY', 'Penalty'), ('REFUND', 'Refund')], max_length=30),
        ),
    ]
