# Generated by Django 6.0 on 2026-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='daily_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pin',
            field=models.CharField(blank=True, help_text='Hashed wallet PIN', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pin_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_withdrawal_limit',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=12),
        ),
    ]
