# Generated by Django 6.0 on 2026-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_wallet_daily_withdrawal_limit_wallet_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_pin_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
