# Generated by Django 6.0 on 2026-02-19 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_pickuprequest_is_verified_scale_and_more'),
        ('wallet', '0008_wallet_last_pin_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('JOB_EARNING', 'Job Earning'), ('SALE_EARNING', 'Sale Earning'), ('COMMISSION_DEDUCTION', 'Commission Deduction'), ('PENALTY', 'Penalty'), ('REFUND', 'Refund'), ('ESCROW_LOCK', 'Escrow Lock'), ('ESCROW_RELEASE', 'Escrow Release'), ('SERVICE_FEE', 'Service Fee')], max_length=30),
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('HELD', 'Held in Escrow'), ('RELEASED', 'Released to Payee'), ('REFUNDED', 'Refunded to Payer')], default='HELD', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_escrows', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_escrows', to=settings.AUTH_USER_MODEL)),
                ('pickup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='logistics.pickuprequest')),
            ],
        ),
    ]
