# Generated by Django 5.2.17 on 2026-09-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0002_collectorperformancesnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=120, unique=True)),
                ("source", models.CharField(default="formasty", max_length=30)),
                ("role", models.CharField(blank=True, max_length=30)),
                ("materials", models.JSONField(default=list)),
                ("area", models.CharField(blank=True, max_length=120)),
                ("current_disposal", models.CharField(blank=True, max_length=50)),
                ("price_now_ghs", models.FloatField(blank=True, null=True)),
                ("anchor30_reaction", models.CharField(blank=True, max_length=30)),
                ("min_payout_range", models.CharField(blank=True, max_length=30)),
                ("pricing_structure_pref", models.CharField(blank=True, max_length=30)),
                ("weighing_trust", models.CharField(blank=True, max_length=30)),
                ("payment_pref", models.CharField(blank=True, max_length=30)),
                ("track_a_fee_range", models.CharField(blank=True, max_length=30)),
                ("volume", models.JSONField(default=dict)),
                ("ewaste_expectations", models.JSONField(default=dict)),
                ("open_feedback", models.TextField(blank=True)),
                ("raw_answers", models.JSONField(default=dict)),
                ("submitted_at", models.DateTimeField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
