# Generated by Django 5.2.17 on 2026-09-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0004_seed_market_survey_responses"),
        ("logistics", "0016_pickuprequest_accepted_at_arrived_at_completed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_lat", models.FloatField()),
                ("pickup_lon", models.FloatField()),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("duration_min", models.FloatField(blank=True, null=True)),
                ("used_real_route", models.BooleanField(default=False)),
                ("online_collector_count", models.PositiveIntegerField(default=0)),
                ("pending_job_count", models.PositiveIntegerField(default=0)),
                ("demand_multiplier", models.FloatField(default=1.0)),
                ("quoted_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "pickup_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_quotes",
                        to="logistics.pickuprequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
