# Generated by Django 4.2.30 on 2026-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0006_seed_market_survey_responses_batch2"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialBuybackPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_type",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("label", models.CharField(max_length=120)),
                ("price_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source", models.CharField(max_length=120)),
                ("source_note", models.TextField(blank=True)),
                ("captured_at", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-captured_at", "-price_per_kg"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialbuybackprice",
            constraint=models.UniqueConstraint(
                fields=("label", "source", "captured_at"),
                name="one_buyback_price_per_item_per_capture",
            ),
        ),
    ]
