# Generated by Django 4.2.30 on 2026-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0008_seed_ghana_buyback_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialbuybackprice",
            name="preparation_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="materialbuybackprice",
            name="price_per_kg_high",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="materialbuybackprice",
            name="price_per_kg_low",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
