# Generated by Django 4.2.30 on 2026-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0010_seed_ghana_buyback_bands"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricequote",
            name="straight_line_km",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
