# Generated by Django 4.2.30 on 2026-09-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0011_pricequote_straight_line_km"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsurveyresponse",
            name="lead_tier",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="marketsurveyresponse",
            name="quiz_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
