# Generated by Django 6.0 on 2026-02-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('PET', 'PET Bottles'), ('HDPE', 'HDPE Plastic'), ('ALUMINUM', 'Aluminum Cans'), ('PAPER', 'Paper/Cardboard'), ('ELECTRONICS', 'E-Waste'), ('METALS', 'Scrap Metal')], max_length=50, unique=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
