# Generated by Django 6.0 on 2026-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_materialmarketprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='e.g. Organic, Hazardous, General', max_length=100, unique=True)),
                ('fee_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='bag', help_text='e.g. bag, kg, liter', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='track',
            field=models.CharField(choices=[('TRACK_A', 'General Waste (Paid Disposal)'), ('TRACK_B', 'Recyclables (Value Buyback)')], db_index=True, default='TRACK_A', max_length=20),
        ),
    ]
