# Generated by Django 6.0 on 2026-02-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_trackaservicefee_listing_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='track',
            field=models.CharField(choices=[('A', 'Paid Disposal (General Waste)'), ('B', 'Value Buyback (Recyclables)')], db_index=True, default='A', max_length=1),
        ),
    ]
