# Generated by Django 5.2.9 on 2026-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_listing_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='track',
            field=models.CharField(choices=[('A', 'Safe Disposal (Pay to Clear)'), ('B', 'Sell Recyclables (Earn Cash)'), ('C', 'Buy Materials')], db_index=True, default='A', max_length=1),
        ),
    ]
