# Generated by Django 6.0 on 2026-03-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_listing_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmarketprice',
            name='material_type',
            field=models.CharField(choices=[('PET', 'PET Bottles'), ('HDPE', 'HDPE Plastic'), ('ALUMINUM', 'Aluminum Cans'), ('PAPER', 'Paper/Cardboard'), ('ELECTRONICS', 'E-Waste'), ('METALS', 'Scrap Metal'), ('PURE_WATER_RUBBERS', 'Pure Water Rubbers')], max_length=50, unique=True),
        ),
    ]
