# Generated by Django 6.0 on 2026-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_materialmarketprice_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialmarketprice',
            name='material_type',
            field=models.CharField(choices=[('PET', 'PET Bottles'), ('HDPE', 'HDPE Plastic'), ('ALUMINUM', 'Aluminum Cans'), ('PAPER', 'Paper/Cardboard'), ('ELECTRONICS', 'E-Waste'), ('METALS', 'Scrap Metal'), ('PURE_WATER_RUBBERS', 'Pure Water Rubbers'), ('PURE_WATER_RUBBERS_BALE', 'Pure Water Rubbers Bale'), ('PLASTIC_BOTTLES', 'Plastic Bottles'), ('PLASTIC_BOTTLES_BALE', 'Plastic Bottles Bale')], max_length=50, unique=True),
        ),
    ]
