# Generated by Django 4.2.30 on 2026-08-10 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0010_alter_materialmarketprice_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
