# Generated by Django 4.2.30 on 2026-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0011_listing_liked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
