# Generated by Django 6.0 on 2025-12-20 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_users', models.IntegerField(default=0)),
                ('online_users', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('active_orders', models.IntegerField(default=0)),
                ('active_rides', models.IntegerField(default=0)),
                ('completed_orders_today', models.IntegerField(default=0)),
                ('completed_rides_today', models.IntegerField(default=0)),
                ('open_tickets', models.IntegerField(default=0)),
                ('resolved_tickets_today', models.IntegerField(default=0)),
                ('api_response_time_ms', models.FloatField(blank=True, null=True)),
                ('database_connections', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('ORDER_CREATED', 'Order Created'), ('ORDER_COMPLETED', 'Order Completed'), ('RIDE_REQUESTED', 'Ride Requested'), ('RIDE_STARTED', 'Ride Started'), ('RIDE_COMPLETED', 'Ride Completed'), ('PAYMENT_MADE', 'Payment Made'), ('USER_VERIFIED', 'User Verified'), ('USER_SUSPENDED', 'User Suspended'), ('SUPPORT_TICKET_CREATED', 'Support Ticket Created'), ('SUPPORT_TICKET_RESOLVED', 'Support Ticket Resolved')], db_index=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'action'], name='admin_dashb_timesta_15a110_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_USER', 'New User Registration'), ('NEW_ORDER', 'New Order'), ('NEW_RIDE', 'New Ride Request'), ('SUPPORT_TICKET', 'New Support Ticket'), ('URGENT_ISSUE', 'Urgent Issue'), ('SYSTEM_ALERT', 'System Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'is_read', '-created_at'], name='admin_dashb_admin_i_a9de90_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('TECHNICAL', 'Technical Issue'), ('PAYMENT', 'Payment Issue'), ('ORDER', 'Order Issue'), ('RIDE', 'Ride Issue'), ('ACCOUNT', 'Account Issue'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='admin_dashb_status_e832c4_idx'), models.Index(fields=['assigned_admin', 'status'], name='admin_dashb_assigne_1e558e_idx')],
            },
        ),
    ]
