# Generated by Django 6.0 on 2026-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('ORDER_CREATED', 'Order Created'), ('ORDER_COMPLETED', 'Order Completed'), ('RIDE_REQUESTED', 'Ride Requested'), ('RIDE_STARTED', 'Ride Started'), ('RIDE_COMPLETED', 'Ride Completed'), ('PAYMENT_MADE', 'Payment Made'), ('USER_VERIFIED', 'User Verified'), ('USER_SUSPENDED', 'User Suspended'), ('SUPPORT_TICKET_CREATED', 'Support Ticket Created'), ('SUPPORT_TICKET_RESOLVED', 'Support Ticket Resolved'), ('WALLET_PIN_CHANGED', 'Wallet PIN Changed'), ('WITHDRAWAL_REQUESTED', 'WithdrawAL Requested'), ('SECURITY_ALERT', 'Security Alert'), ('ADMIN_ACTION', 'Admin Action')], db_index=True, max_length=50),
        ),
    ]
