# Generated by Django 6.0 on 2026-02-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_activitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promos/')),
                ('image_url', models.URLField(blank=True, help_text='Alternative to uploaded image', max_length=500, null=True)),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('badge_color', models.CharField(default='#2E7D32', max_length=20)),
                ('target_role', models.CharField(choices=[('ALL', 'All Users'), ('SELLER', 'Sellers/Disposers'), ('COLLECTOR', 'Collectors'), ('RECYCLER', 'Recyclers')], default='ALL', max_length=20)),
                ('action_type', models.CharField(default='NAVIGATE', help_text='e.g., NAVIGATE, URL', max_length=50)),
                ('action_value', models.CharField(help_text='e.g., Pickups, ListingDetail, https://google.com', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
