# Generated by Django 4.2.30 on 2026-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_dashboard", "0004_onboardingscreen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingscreen",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="promocard",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
