"""
Django settings for revesta_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# PyMySQL compatibility patch for XAMPP/MariaDB 10.4
# Allows Django 6 to work with MariaDB < 10.6 by spoofing the version string
try:
    import pymysql
    pymysql.install_as_MySQLdb()
    pymysql.version_info = (10, 6, 0, "final", 0)
except ImportError:
    pass

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# The insecure fallback only applies in local dev (DEBUG=True) - it used to
# apply unconditionally, which meant a misconfigured production deploy would
# silently sign JWTs (SIMPLE_JWT['SIGNING_KEY'] below) and sessions with a
# key sitting in the git history instead of failing loudly. Render already
# sets a real SECRET_KEY for every service (see render.yaml), so this never
# fires there.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-db+coeekbvf0!-21p2rdol2bq074dqze=h$hizcfc12-x5w56m'
    else:
        raise ImproperlyConfigured('SECRET_KEY environment variable must be set when DEBUG=False.')

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')
if '*' in ALLOWED_HOSTS and not DEBUG:
    # If in production and still wildcard, restrict it if possible or warn
    print("WARNING: ALLOWED_HOSTS is '*' in production. Please set this in environment variables.")

# Trust Railway/Render domains automatically
RAILWAY_STATIC_URL = os.environ.get('RAILWAY_STATIC_URL')
if 'RENDER_EXTERNAL_HOSTNAME' in os.environ:
    ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))
if RAILWAY_STATIC_URL:
    ALLOWED_HOSTS.append(RAILWAY_STATIC_URL.replace('https://', '').replace('http://', ''))

# Production Security Headers
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    X_FRAME_OPTIONS = 'DENY'

# Encryption Key for sensitive data (e.g. KYC ID numbers)
FERNET_KEY = os.environ.get('FERNET_KEY', b'osLlL5AzQozSnG3c6TLOptUE1lAr_3kO3nyiOO88b38=')

# Used server-side for real driving-time/distance estimates instead of a
# straight-line haversine guess. Not set by default - without it,
# estimate_price() falls back to the haversine calculation it always used.
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'corsheaders',
    'channels',
    'drf_spectacular',  # API documentation
    'django_filters',   # Advanced filtering
    'cloudinary_storage',  # Media uploads - see DEFAULT_FILE_STORAGE below
    'cloudinary',
    # Local apps
    'users',
    'market',
    'logistics',
    'chat',
    'admin_dashboard',  # Admin dashboard system
    'wallet',  # Enabled for mobile app
    'moderation',  # User blocking + content reporting
    'intelligence',  # AI prediction logging - see intelligence/models.py
    'ratings',  # Provider/collector ratings on completed pickups
]

MIDDLEWARE = [
    'revesta_backend.middleware.RequestLoggingMiddleware', # Custom debugging middleware
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Add WhiteNoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'revesta_backend.middleware.ActivityTrackingMiddleware',
]

ROOT_URLCONF = 'revesta_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'users' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'revesta_backend.wsgi.application'
ASGI_APPLICATION = 'revesta_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

_db_config = dj_database_url.config(
    default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
    conn_max_age=600,
    conn_health_checks=True,
)

# Add MySQL-specific production options when using MySQL
if _db_config.get('ENGINE') == 'django.db.backends.mysql':
    _db_config.setdefault('OPTIONS', {})
    _db_config['OPTIONS'].update({
        'charset': 'utf8mb4',
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        'connect_timeout': 10,
    })
    # Use our custom backend that skips the MariaDB version check (XAMPP ships 10.4)
    _db_config['ENGINE'] = 'revesta_backend.mysql_compat'

DATABASES = {'default': _db_config}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Additional static files locations
STATICFILES_DIRS = [
    # Add other static directories here
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

# CORS configuration
# Was unconditionally True, which - combined with CORS_ALLOW_CREDENTIALS
# below - let django-cors-headers reflect any site's Origin header instead
# of restricting to an allowlist, so any website could make credentialed
# requests against this API using a logged-in user's browser. Only allow
# everything in local dev now; production uses the explicit allowlist below.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://localhost:5174",
    # Admin dashboard (admin/, deployed on Vercel).
    "https://revest-gh-zh89.vercel.app",
]
if os.environ.get('CORS_ALLOWED_ORIGINS'):
    CORS_ALLOWED_ORIGINS.extend(os.environ.get('CORS_ALLOWED_ORIGINS').split(','))

if CORS_ALLOW_ALL_ORIGINS and not DEBUG:
    print("WARNING: CORS_ALLOW_ALL_ORIGINS is True in production!")

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = ["http://localhost:5173", "http://127.0.0.1:5173", "http://192.168.100.7:8000", "http://localhost:3000", "http://localhost:5174", "http://localhost:8000", "https://revest-gh-zh89.vercel.app"]
if 'RENDER_EXTERNAL_HOSTNAME' in os.environ:
    CSRF_TRUSTED_ORIGINS.append(f"https://{os.environ.get('RENDER_EXTERNAL_HOSTNAME')}")
if RAILWAY_STATIC_URL:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RAILWAY_STATIC_URL}")
if 'CORS_ALLOWED_ORIGINS' in os.environ:
    # Also trust frontend origins for CSRF (though mainly backend needed for Admin)
    for origin in os.environ.get('CORS_ALLOWED_ORIGINS').split(','):
        CSRF_TRUSTED_ORIGINS.append(origin)

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/minute',  # Limit for unauthenticated users
        'user': '10000/day',   # Increased for polling admin dashboard
        'register': '5/minute', # Strict limit for registration
        'login': '10/minute',    # Strict limit for login (brute-force protection)
        'otp': '10/minute',      # OTP send/verify endpoints - resist code guessing
        'otp_identifier': '30/hour', # Increased for testing (originally 3/hour)
        'wallet': '100/minute',   # Increased for usability
    },
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailOrPhoneBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Redis Cache Configuration
# Redis Cache Configuration
if 'REDIS_URL' in os.environ:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ.get('REDIS_URL'),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }

# Redis Channel Layer
if 'REDIS_URL' in os.environ:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.environ.get('REDIS_URL')],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Uploads (profile pictures, listing photos, KYC documents, pickup
# verification photos) default to local disk above, which on Render's free
# tier is small and doesn't survive a redeploy - a real production bug
# (profile updates with a photo failing outright once the disk filled).
# Cloudinary's free tier fixes both problems and needs no code changes
# beyond this file: every ImageField/FileField save just goes there instead
# once CLOUDINARY_URL is set. Until that env var exists, uploads keep using
# local disk exactly as before - nothing breaks for anyone who hasn't set
# this up yet (e.g. local development).
if os.environ.get('CLOUDINARY_URL'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Google Sign-In.
# Every OAuth client that is allowed to authenticate against this backend. A
# token is only accepted if its audience is one of these, which is what stops
# a Google token minted for some *other* app being replayed here. Defaults are
# the clients in mobile/google-services.json; override per environment with a
# comma-separated GOOGLE_OAUTH_CLIENT_IDS.
GOOGLE_OAUTH_CLIENT_IDS = [
    cid.strip() for cid in os.environ.get(
        'GOOGLE_OAUTH_CLIENT_IDS',
        # Android client (com.revesta.mobile)
        '132479987352-0mb8h8gaaj2c8qg8jdebgd7u7nsglau3.apps.googleusercontent.com,'
        # Web client
        '132479987352-q4qc0odon0kcvb1vbs5gb8m385soge6v.apps.googleusercontent.com'
    ).split(',') if cid.strip()
]

# Paystack
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY')

# Hubtel SMS
HUBTEL_CLIENT_ID = os.environ.get('HUBTEL_CLIENT_ID')
HUBTEL_CLIENT_SECRET = os.environ.get('HUBTEL_CLIENT_SECRET')
HUBTEL_FROM = os.environ.get('HUBTEL_FROM', 'Revesta')

# Email Configuration
# Use Resend if API key is available (bypasses SMTP port blocking)
import logging
email_logger = logging.getLogger('revesta.email')

# Absolute base URL of this backend deployment - used to build absolute
# asset URLs (e.g. the logo image in transactional emails) since email
# clients fetch images over HTTP and can't resolve relative paths.
BACKEND_URL = os.environ.get('BACKEND_URL', 'https://revest-gh.onrender.com')

if os.environ.get('RESEND_API_KEY'):
    EMAIL_BACKEND = 'users.email_backend.ResendBackend'
    RESEND_API_KEY = os.environ.get('RESEND_API_KEY')
    # Resend's sandbox sender (onboarding@resend.dev) only delivers to the
    # Resend account owner's own inbox - fine for testing, useless for real
    # users. Once a domain is verified on Resend, set DEFAULT_FROM_EMAIL on
    # Render (e.g. noreply@yourdomain.com) and it takes effect immediately -
    # no code change needed.
    DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'onboarding@resend.dev')
    email_logger.info(f"✓ Email configured with Resend API (key length: {len(RESEND_API_KEY)}, from: {DEFAULT_FROM_EMAIL})")
else:
    # Fallback to SMTP (for local development)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_USE_SSL = False
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'noreply@revesta.com')
    
    if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
        email_logger.info(f"✓ Email configured with SMTP ({EMAIL_HOST}:{EMAIL_PORT})")
    else:
        email_logger.warning("⚠ Email NOT configured - missing RESEND_API_KEY or SMTP credentials")

EMAIL_TIMEOUT = 5  # Timeout in seconds to prevent hanging

# JWT Configuration for Mobile API
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# API Documentation Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'ReVesta API',
    'DESCRIPTION': 'RESTful API for ReVesta mobile application - waste management and recycling platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/v1',
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Local development server'},
        {'url': 'https://your-app.onrender.com', 'description': 'Production server'},
    ],
    'TAGS': [
        {'name': 'auth', 'description': 'Authentication endpoints'},
        {'name': 'users', 'description': 'User profile and management'},
        {'name': 'market', 'description': 'Marketplace listings'},
        {'name': 'logistics', 'description': 'Pickup requests and tracking'},
        {'name': 'chat', 'description': 'Messaging system'},
        {'name': 'wallet', 'description': 'Financial transactions'},
        {'name': 'admin', 'description': 'Admin dashboard (staff only)'},
    ],
}

# Mobile App Configuration
MOBILE_APP_SCHEME = os.environ.get('MOBILE_APP_SCHEME', 'revesta://')  # For deep linking
