# Generated by Django 6.0 on 2025-12-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='duration_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
