# Generated by Django 6.0 on 2026-01-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_pickuprequest_actual_price_pickuprequest_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('DIGITAL', 'Digital (In-App)')], default='CASH', max_length=20),
        ),
    ]
