# Generated by Django 6.0 on 2026-02-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_pickuprequest_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='destination_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='destination_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='destination_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
