# Generated by Django 6.0 on 2026-02-15 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_pickuprequest_destination_address_and_more'),
        ('market', '0003_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_requests', to='market.listing'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='waste_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
