# Generated by Django 6.0 on 2026-02-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_pickuprequest_delivery_fee_pickuprequest_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='ai_verified_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='bag_size',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small Bag'), ('MEDIUM', 'Medium Bag'), ('LARGE', 'Large Bag'), ('XLARGE', 'Extra Large / Bulk')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='manual_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='track_type',
            field=models.CharField(choices=[('A', 'Paid Disposal (General Waste)'), ('B', 'Value Buyback (Recyclables)')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='verification_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
