# Generated by Django 6.0 on 2026-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_pickuprequest_ai_verified_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='is_verified_scale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='scale_photo',
            field=models.ImageField(blank=True, null=True, upload_to='scale_photos/'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='track',
            field=models.CharField(choices=[('TRACK_A', 'General Waste (Paid Disposal)'), ('TRACK_B', 'Recyclables (Value Buyback)')], db_index=True, default='TRACK_A', max_length=20),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='verification_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
