# Generated by Django 6.0 on 2026-02-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_pickuprequest_is_verified_scale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='is_verified_scale',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='scale_photo',
        ),
        migrations.RemoveField(
            model_name='pickuprequest',
            name='track',
        ),
    ]
