# Generated by Django 5.2.9 on 2026-02-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_remove_pickuprequest_is_verified_scale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='track_type',
            field=models.CharField(choices=[('A', 'Safe Disposal (Pay to Clear)'), ('B', 'Sell Recyclables (Earn Cash)'), ('C', 'Buy Materials')], default='A', max_length=1),
        ),
    ]
