# Generated by Django 6.0 on 2026-02-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_pickuprequest_track_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pickup_requests/'),
        ),
    ]
