# Generated by Django 6.0 on 2026-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_pickuprequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='is_disposer_paid',
            field=models.BooleanField(default=False),
        ),
    ]
