# Generated by Django 4.2.30 on 2026-08-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0012_pickuprequest_is_disposer_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuprequest",
            name="last_location_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
