# Generated by Django 4.2.30 on 2026-08-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0013_pickuprequest_last_location_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuprequest",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
