# Generated by Django 4.2.30 on 2026-08-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0014_pickuprequest_pickup_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuprequest",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
