# Generated by Django 6.0 on 2026-01-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_auth_provider_user_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_certification',
            field=models.ImageField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
