# Generated by Django 6.0 on 2026-02-17 16:13

from django.db import migrations


def create_admin(apps, schema_editor):
    from django.contrib.auth import get_user_model
    User = get_user_model()
    username = 'admin_test'
    email = 'admin_test@example.com'
    password = 'AdminPassword123'
    
    if not User.objects.filter(username=username).exists():
        user = User.objects.create_superuser(
            username=username,
            email=email,
            password=password
        )
        user.role = 'ADMIN'
        user.save()
        print(f"Admin user '{username}' created with password '{password}'")
    else:
        user = User.objects.get(username=username)
        user.set_password(password)
        user.is_staff = True
        user.is_superuser = True
        user.role = 'ADMIN'
        user.save()
        print(f"Admin user '{username}' updated with password '{password}'")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_last_device_id_user_mfa_enabled'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
