# Generated by Django 6.0 on 2026-02-17 16:13

from django.db import migrations


# This migration used to create a superuser 'admin_test' with a hardcoded
# password on every environment that ran migrations, and to reset that
# password back to the known value on each subsequent run. It has been
# neutralised for two reasons:
#
# 1. It could not run at all on a fresh database. It called get_user_model(),
#    which returns the *current* User model rather than the historical one for
#    this point in history, so the INSERT referenced columns that don't exist
#    until migration 0016 (last_active_at). `manage.py migrate` on a new
#    database failed with "table users_user has no column named
#    last_active_at", breaking new deployments, fresh dev setups and CI.
#
# 2. Even where it did run, seeding a known-password superuser into every
#    environment - production included - is a standing credential risk.
#
# The migration node is kept (rather than deleted) so databases that already
# recorded it stay consistent. Environments that ran the old version still
# have the 'admin_test' account; it should be removed or have its password
# rotated manually. Create real admins with `manage.py createsuperuser`.


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_last_device_id_user_mfa_enabled'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
