# Generated by Django 4.2.30 on 2026-08-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_userfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_active_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_reengagement_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
