# Generated by Django 4.2.30 on 2026-08-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_last_active_at_user_last_reengagement_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverification",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
