# Generated by Django 4.2.30 on 2026-08-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_phoneverification_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
